### ISSUE TITLE
Code in Code_11_3.cs is not compiling

### ISSUE THREAD

**Issue by Wasp3r** [PacktPublishing/Hands-On-Object-Oriented-Programming-with-CSharp#2]
Hello,

I'm trying to get the code from chapter 11 working, but I get compile errors. I copied the code from this git, but it's still not working. Am I doing something wrong?

**Comment by sonam-packt** [comment]
Hi @Wasp3r 

could you please try to download the zip file from the repository and then try to execute it, I think it could resolve the issue.
